# Site settings
title: Chuck Groom
email: chuck.groom+portfolio@gmail.com
url: https://chuckgroom.com
description: "Chuck Groom, an experienced software entrepreneur and CTO in New York City"
keywords: "CTO, Architect, Engineering Manager, Software Engineer, Python, Ruby, Machine Learning, Deep Learning, VR, AR, New York City, NYC, Startups"
skills: "Entrepreneur, CTO in New York City"
meta_author: Groom Charles

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chuck Groom
  location: 
  social: Around the Web
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/cgroom/
  - title: medium
    url: https://medium.com/@cgroom

# Postal address (add as many lines as necessary)
address:
  - line:

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
